title: AI/ML/DS Conference Deadlines 4 Africans # 
# email: vukosi.marivate@cs.up.ac.za
description: Countdowns to AI/ML/DS conference deadlines for Africans
author: Mpho Mokoatle, Avashlin Moodley, Vukosi Marivate

domain: "mldsafrica.co.za"
baseurl: ""

twitter_username: dsfsi
twitter_hashtag: africanmachinelearning
github_username: dsfsi
github_repo: deadlines

markdown: kramdown
ga_id: UA-137561504-1

include: ['_pages']
